name: Build

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["nrf52840"]

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Checkout code
      uses: actions/checkout@v2  
    - name: Checkout adafruit/ci-arduino
      uses: actions/checkout@v2
      with:
         repository: hathach/ci-arduino
         ref: build-bsp
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
      
    - name: Failed on purpose
      run: exit 1
